### ISSUE TITLE
[Bug] TextInput status icon displayed oddly

### ISSUE THREAD

**Issue by meissadia** [cfpb/design-stories#102]
Icon should show inline with the text field (last name), instead we see it seemingly associated with the header below (email)

![Image](https://github.com/cfpb/design-stories/assets/2592907/79176d6e-65fe-4b01-9954-39d546c69daa)

**Comment by meissadia** [comment]
Maybe this is by design? https://cfpb.github.io/design-system/components/notifications#success-notification-field-level
 
I had assumed the icon should display next to the field label but it seems like the design is actually to have a status icon + message below the input field.

**Comment by natalia-fitzgerald** [comment]
This looks correct in the library. 
![Screenshot 2023-08-07 at 2 34 17 PM](https://github.com/cfpb/design-stories/assets/77348967/4545d277-9834-46e9-8f38-d23450f729e3)

**Comment by meissadia** [comment]
This seems to have been a missing prop in the prototype implementation from the original screenshot.  
 
 Closing this.
