### ISSUE TITLE
[Bug] Max width for text

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-stories#120]
The max with for text on the website is 670px wide. Components with text inside of them should include this max width in the code. 

## Current behavior
![Screenshot 2023-08-07 at 2 44 19 PM](https://github.com/cfpb/design-stories/assets/77348967/b3c3817e-4db9-4bd7-a090-1cae7fdf8478)

## Expected behavior
![Screenshot 2023-08-07 at 2 44 40 PM](https://github.com/cfpb/design-stories/assets/77348967/5858c1a3-d618-4b99-816c-d7756cc1f51e)

In the filing platform mock-ups (and generally on our website) these components will be 770px in width. So, there won't be the empty space you see above in the "Expected behavior." 

**It would look more like this:** 
![Screenshot 2023-08-07 at 2 45 37 PM](https://github.com/cfpb/design-stories/assets/77348967/51800718-3de2-47cb-8730-af0957a58f9c)

#### Design System example: 
[Expandable](https://cfpb.github.io/design-system/components/expandables#standard-expandable): Expandable header and paragraph text set to 670px

**Comment by meissadia** [comment]
That width restriction is something that applies to [text content within a CFPB Layout](https://github.com/cfpb/design-system/blob/main/packages/cfpb-layout/src/cfpb-layout.less#L210-L223).
 
I do see this setting duplicated in a few places but it is generally a broadly applied rule and not something specified per component. 
 
![Screenshot 2023-08-14 at 3 13 30 PM](https://github.com/cfpb/design-stories/assets/2592907/503697fc-1eff-4942-a6d7-b058e1f5edac)

It looks like Ans encountered this same issue while building the DS documentation pages and [had to set this width restriction for all `.ds-content`](https://github.com/cfpb/design-system/blob/main/docs/assets/css/main.less#L109-L117), so I will try to implement something similar.

**Comment by meissadia** [comment]
I've added a CSS rule to [restrict width in Storybook](https://github.com/cfpb/design-stories/pull/149/files#diff-54e9da41db6212e21c9bc824c4ab3b9f3ad37b4d9cae8c5e4c476a015bb77f77R7-R29).
 
I'll need to revisit our [DSR Layout](https://github.com/cfpb/design-stories/tree/main/src/components/Layout) components to ensure they have the correct classes for this width restriction to apply.
