### ISSUE TITLE
Easily view an element's CSS within Storybook

### ISSUE THREAD

**Issue by meissadia** [cfpb/design-stories#123]
Design team has expressed the desire to be able to easily view an element's CSS within Storybook without having to resort to using the browser's inspector/dev tools. 

This Storybook addon looks promising: https://storybook.js.org/addons/display-element-css
- Install addon
- Deploy preview
- Demo to Design team

**Comment by natalia-fitzgerald** [comment]
I love this idea and wonder whether it could help with a Design System problem we have where specs are manually entered rather than pulled from the code (which means specs are frequently out of sync with what's actually happening on our site).

**Comment by natalia-fitzgerald** [comment]
@meissadia 
What do we need to do to prioritize this feature? It would be helpful with the work I'm doing now reviewing the components.

**Comment by meissadia** [comment]
@natalia-fitzgerald I will take this up now

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Will this feature show up as a tab like what is shown here for HTML?
![Screenshot 2023-08-09 at 3 31 00 PM](https://github.com/cfpb/design-stories/assets/77348967/ed71fa4e-4499-4774-b5b5-a0ae5a085d99)

**Comment by meissadia** [comment]
Unfortunately the addon is broken. 
 
I'm not finding any alternative addons that could provide the same functionality so I'm trying to debug the source code for `[display-element-css](https://storybook.js.org/addons/display-element-css)` to see if I can make it work.

**Comment by meissadia** [comment]
I've [opened an issue](https://github.com/AmyScript/storybook-addon/issues/4) on the repo for `display-element-css` and [proposed a solution](https://github.com/AmyScript/storybook-addon/issues/4#issuecomment-1672243210) to get the addon working again.  
 
The developer hasn't been [active on github since July](https://github.com/AmyScript?tab=overview&from=2023-06-01&to=2023-10-30) so we may be out of luck with getting this fixed anytime soon.

**Comment by meissadia** [comment]
@natalia-fitzgerald When the addon *does* work, you would
- Click the `eyeball` icon to open the `Display Element CSS` tab
- Click on an element to see it's specified CSS
 
I do see some limitations to the addon, particularly in the way that it decides which CSS to show / exclude.
 
In the demo video below, it works well for the Hero component.  

https://github.com/cfpb/design-stories/assets/2592907/73881bac-2073-43e1-ba49-de8e56d7bbee

**Comment by contolini** [comment]
@meissadia I forked it to https://github.com/cfpb/storybook-addon-display-element-css. If you don't have luck with fixing the original add-on feel free to push to main on the fork and install it with `yarn add cfpb/storybook-addon-display-element-css`
