### ISSUE TITLE
[Component] Call-to-action links

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-stories#145]
Add call-to-action link to the component library 
https://cfpb.github.io/design-system/components/links#call-to-action-links

## Screenshots
<img width="796" alt="Screenshot 2023-08-14 at 1 55 07 PM" src="https://github.com/cfpb/design-stories/assets/77348967/5999bd27-5385-4306-a27d-3f8934c341b9">

If the [List link](https://cfpb.github.io/design-stories/?path=/story/components-link--list-link) is meant to be the code that is used for a "Call-to-action link" we need to update the weight to Medium.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Can you check whether the [List links](https://cfpb.github.io/design-system/components/lists#link-list) and [Call-to-action links](https://cfpb.github.io/design-system/components/links#call-to-action-links) are exactly the same thing from a code perspective?

**Comment by meissadia** [comment]
@natalia-fitzgerald Yes, Call-to-action == list links. 
 
The font-weight mismatch is already addressed in PR https://github.com/cfpb/design-stories/pull/152

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Ok, I will close this issue because we have already included this component with the links component. https://cfpb.github.io/design-stories/?path=/docs/components-link--overview#list-link

I will conduct a separate review of that specific component and add feedback there.
