### ISSUE TITLE
Bug: Multi-select keyboard tabbing

### ISSUE THREAD

**Issue by contolini** [cfpb/design-stories#28]
The [multi-select](https://cfpb.github.io/design-stories/?path=/story/components-dropdown--multi-select) has solid keyboard support but it looks like hitting `tab` when the dropdown is open causes the current item to be selected.

![multiselect](https://user-images.githubusercontent.com/1060248/233150177-f1b414de-bccf-47bb-8374-9eeef09549c5.gif)

## Expected Behavior

- Hitting `tab` when a dropdown item is focused moves focus to the next item OR
- Hitting `tab` when a dropdown item is focused exits the dropdown (and moves to the next form element on the page)

## Actual Behavior

- Hitting `tab` when a dropdown item is selected selects it

## Steps to Reproduce the Problem

  1. Click on the [multi-select](https://cfpb.github.io/design-stories/?path=/story/components-dropdown--multi-select) to open it.
  1. Hit `tab`.

## Notes

- See the [DS multi-select](https://cfpb.github.io/design-system/components/dropdowns-and-multiselects#multiselects-1) for inspiration. It has checkboxes so it behaves a little differently.

**Comment by meissadia** [comment]
Doesn't look like this is an easy fix with the `react-select` library used to implement this.  That said, after the success we had with integrating the CFPB DS Expandable, maybe we can reimplement this component utilizing the CFPB DS Multiselect JS.
