### ISSUE TITLE
[Component] CFPB Grid

### ISSUE THREAD

**Issue by meissadia** [cfpb/design-stories#66]
https://cfpb.github.io/design-system/foundation/grid

**Comment by anselmbradford** [comment]
FYI I have been working on new utility classes using CSS grid for major page layouts (see https://github.com/cfpb/consumerfinance.gov/pull/7754 and https://github.com/cfpb/consumerfinance.gov/pull/7629). 
Eventually the intention would be that these will work their way into the DS grid. For now, I would avoid any complicated layouts built on the DS grid if possible and view it as kind of deprecated.

**Comment by meissadia** [comment]
> FYI I have been working on new utility classes using CSS grid for major page layouts (see [cfpb/consumerfinance.gov#7754](https://github.com/cfpb/consumerfinance.gov/pull/7754) and [cfpb/consumerfinance.gov#7629](https://github.com/cfpb/consumerfinance.gov/pull/7629)). Eventually the intention would be that these will work their way into the DS grid. For now, I would avoid any complicated layouts built on the DS grid if possible and view it as kind of deprecated.

@anselmbradford Appreciate the heads up!  I've got a rough working version already implemented in https://github.com/cfpb/design-stories/pull/67.  My understanding from chats with @natalia-fitzgerald is that all the new SBL layouts are being based on the CFPB 12-column grid.  So if it is being deprecated then it sounds like there are things that would need re-thinking.

**Comment by anselmbradford** [comment]
> @anselmbradford Appreciate the heads up! I've got a rough working version already implemented in https://github.com/cfpb/design-stories/pull/67. My understanding from chats with @natalia-fitzgerald is that all the new SBL layouts are being based on the CFPB 12-column grid. So if it is being deprecated then it sounds like there are things that would need re-thinking.

The 12-column grid can still be a reference, but the implementation likely will evolve. I think mirroring what's in the DS for now is fine, but if you can avoid over use of the `.grid_column()` mixin, that's probably preferable.

**Comment by meissadia** [comment]
> The 12-column grid can still be a reference, but the implementation likely will evolve. I think mirroring what's in the DS for now is fine, but if you can avoid over use of the `.grid_column()` mixin, that's probably preferable.
 
That mixin is, unfortunately, the foundation of my [cuurent implementation](https://github.com/cfpb/design-stories/blob/32c209cb0d0f48e2f07b72f087ccffc0f22ec227/src/components/Grid.less) so I'll need to explore alternatives.
